type StreetType = {
  name: string;
  farbe: string;
  preis: number;
  hypothek: number;
  hypothekisiert: boolean;
  anzahlHaus: number;
  miete: number;
  mieteGesamt: number;
  miete1Haus: number;
  miete2Haus: number;
  miete3Haus: number;
  miete4Haus: number;
  mieteHotel: number;
  bauenKosten: number;
  straße: boolean;
  bahnhof: boolean;
  sonderstraße: boolean;
};

export const streetArray: StreetType[] = [
  {
    name: "Badstraße",
    farbe: "braun",
    preis: 60,
    hypothek: 30,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 2,
    mieteGesamt: 4,
    miete1Haus: 10,
    miete2Haus: 30,
    miete3Haus: 90,
    miete4Haus: 160,
    mieteHotel: 250,
    bauenKosten: 50,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
  },
  {
    name: "Turmstraße",
    farbe: "braun",
    preis: 60,
    hypothek: 30,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 4,
    mieteGesamt: 8,
    miete1Haus: 20,
    miete2Haus: 60,
    miete3Haus: 180,
    miete4Haus: 320,
    mieteHotel: 450,
    bauenKosten: 50,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
  },
  {
    name: "Chausseestraße",
    farbe: "hellblau",
    preis: 100,
    hypothek: 50,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 6,
    mieteGesamt: 12,
    miete1Haus: 30,
    miete2Haus: 90,
    miete3Haus: 270,
    miete4Haus: 400,
    mieteHotel: 550,
    bauenKosten: 50,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
  },
  {
    name: "Elisenstraße",
    farbe: "hellblau",
    preis: 100,
    hypothek: 50,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 6,
    mieteGesamt: 12,
    miete1Haus: 30,
    miete2Haus: 90,
    miete3Haus: 270,
    miete4Haus: 400,
    mieteHotel: 550,
    bauenKosten: 50,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
  },
  {
    name: "Poststraße",
    farbe: "hellblau",
    preis: 120,
    hypothek: 60,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 8,
    mieteGesamt: 16,
    miete1Haus: 40,
    miete2Haus: 100,
    miete3Haus: 300,
    miete4Haus: 450,
    mieteHotel: 600,
    bauenKosten: 50,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
  },
  {
    name: "Seestraße",
    farbe: "pink",
    preis: 140,
    hypothek: 70,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 10,
    mieteGesamt: 20,
    miete1Haus: 50,
    miete2Haus: 150,
    miete3Haus: 450,
    miete4Haus: 625,
    mieteHotel: 750,
    bauenKosten: 100,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
  },
  {
    name: "Hafenstraße",
    farbe: "pink",
    preis: 140,
    hypothek: 70,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 10,
    mieteGesamt: 20,
    miete1Haus: 50,
    miete2Haus: 150,
    miete3Haus: 450,
    miete4Haus: 625,
    mieteHotel: 750,
    bauenKosten: 100,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
  },
  {
    name: "Neue Straße",
    farbe: "pink",
    preis: 160,
    hypothek: 80,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 12,
    mieteGesamt: 24,
    miete1Haus: 60,
    miete2Haus: 180,
    miete3Haus: 500,
    miete4Haus: 700,
    mieteHotel: 900,
    bauenKosten: 100,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
  },
  {
    name: "Münchener Straße",
    farbe: "orange",
    preis: 180,
    hypothek: 90,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 14,
    mieteGesamt: 28,
    miete1Haus: 70,
    miete2Haus: 200,
    miete3Haus: 550,
    miete4Haus: 750,
    mieteHotel: 950,
    bauenKosten: 100,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
  },
  {
    name: "Wiener Straße",
    farbe: "orange",
    preis: 180,
    hypothek: 90,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 14,
    mieteGesamt: 28,
    miete1Haus: 70,
    miete2Haus: 200,
    miete3Haus: 550,
    miete4Haus: 750,
    mieteHotel: 950,
    bauenKosten: 100,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
  },
  {
    name: "Berliner Straße",
    farbe: "orange",
    preis: 200,
    hypothek: 100,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 16,
    mieteGesamt: 32,
    miete1Haus: 80,
    miete2Haus: 220,
    miete3Haus: 600,
    miete4Haus: 800,
    mieteHotel: 1000,
    bauenKosten: 100,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
  },
];
