export type StreetType = {
  name: string;
  farbe: string;
  preis: number;
  hypothek: number;
  hypothekisiert: boolean;
  anzahlHaus: number;
  miete: number;
  mieteGesamt: number;
  miete1Haus: number;
  miete2Haus: number;
  miete3Haus: number;
  miete4Haus: number;
  mieteHotel: number;
  bauenKosten: number;
  straße: boolean;
  bahnhof: boolean;
  sonderstraße: boolean;
  takenBy: undefined | string;
};

export enum StreetColors {
  Braun = "#965337",
  Hellblau = "#AAE1F3",
  Pink = "#D83996",
  Orange = "#F7941D",
  Rot = "#ED1B24",
  Gelb = "yellow",
  Grün = "#1FB25A",
  Blau = "#0072BE",
  Schwarz = "#100615",
  Weiß = "grey",
}

export const streetArray: StreetType[] = [
  {
    name: "Badstraße",
    farbe: StreetColors.Braun,
    preis: 60,
    hypothek: 30,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 2,
    mieteGesamt: 4,
    miete1Haus: 10,
    miete2Haus: 30,
    miete3Haus: 90,
    miete4Haus: 160,
    mieteHotel: 250,
    bauenKosten: 50,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
    takenBy: undefined,
  },
  {
    name: "Turmstraße",
    farbe: StreetColors.Braun,
    preis: 60,
    hypothek: 30,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 4,
    mieteGesamt: 8,
    miete1Haus: 20,
    miete2Haus: 60,
    miete3Haus: 180,
    miete4Haus: 320,
    mieteHotel: 450,
    bauenKosten: 50,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
    takenBy: undefined,
  },
  {
    name: "Chausseestraße",
    farbe: StreetColors.Hellblau,
    preis: 100,
    hypothek: 50,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 6,
    mieteGesamt: 12,
    miete1Haus: 30,
    miete2Haus: 90,
    miete3Haus: 270,
    miete4Haus: 400,
    mieteHotel: 550,
    bauenKosten: 50,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
    takenBy: undefined,
  },
  {
    name: "Elisenstraße",
    farbe: StreetColors.Hellblau,
    preis: 100,
    hypothek: 50,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 6,
    mieteGesamt: 12,
    miete1Haus: 30,
    miete2Haus: 90,
    miete3Haus: 270,
    miete4Haus: 400,
    mieteHotel: 550,
    bauenKosten: 50,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
    takenBy: undefined,
  },
  {
    name: "Poststraße",
    farbe: StreetColors.Hellblau,
    preis: 120,
    hypothek: 60,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 8,
    mieteGesamt: 16,
    miete1Haus: 40,
    miete2Haus: 100,
    miete3Haus: 300,
    miete4Haus: 450,
    mieteHotel: 600,
    bauenKosten: 50,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
    takenBy: undefined,
  },
  {
    name: "Seestraße",
    farbe: StreetColors.Pink,
    preis: 140,
    hypothek: 70,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 10,
    mieteGesamt: 20,
    miete1Haus: 50,
    miete2Haus: 150,
    miete3Haus: 450,
    miete4Haus: 625,
    mieteHotel: 750,
    bauenKosten: 100,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
    takenBy: undefined,
  },
  {
    name: "Hafenstraße",
    farbe: StreetColors.Pink,
    preis: 140,
    hypothek: 70,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 10,
    mieteGesamt: 20,
    miete1Haus: 50,
    miete2Haus: 150,
    miete3Haus: 450,
    miete4Haus: 625,
    mieteHotel: 750,
    bauenKosten: 100,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
    takenBy: undefined,
  },
  {
    name: "Neue Straße",
    farbe: StreetColors.Pink,
    preis: 160,
    hypothek: 80,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 12,
    mieteGesamt: 24,
    miete1Haus: 60,
    miete2Haus: 180,
    miete3Haus: 500,
    miete4Haus: 700,
    mieteHotel: 900,
    bauenKosten: 100,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
    takenBy: undefined,
  },
  {
    name: "Münchener Straße",
    farbe: StreetColors.Orange,
    preis: 180,
    hypothek: 90,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 14,
    mieteGesamt: 28,
    miete1Haus: 70,
    miete2Haus: 200,
    miete3Haus: 550,
    miete4Haus: 750,
    mieteHotel: 950,
    bauenKosten: 100,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
    takenBy: undefined,
  },
  {
    name: "Wiener Straße",
    farbe: StreetColors.Orange,
    preis: 180,
    hypothek: 90,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 14,
    mieteGesamt: 28,
    miete1Haus: 70,
    miete2Haus: 200,
    miete3Haus: 550,
    miete4Haus: 750,
    mieteHotel: 950,
    bauenKosten: 100,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
    takenBy: undefined,
  },
  {
    name: "Berliner Straße",
    farbe: StreetColors.Orange,
    preis: 200,
    hypothek: 100,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 16,
    mieteGesamt: 32,
    miete1Haus: 80,
    miete2Haus: 220,
    miete3Haus: 600,
    miete4Haus: 800,
    mieteHotel: 1000,
    bauenKosten: 100,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
    takenBy: undefined,
  },
  {
    name: "Theaterstraße",
    farbe: StreetColors.Rot,
    preis: 220,
    hypothek: 110,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 18,
    mieteGesamt: 36,
    miete1Haus: 90,
    miete2Haus: 250,
    miete3Haus: 700,
    miete4Haus: 875,
    mieteHotel: 1050,
    bauenKosten: 150,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
    takenBy: undefined,
  },
  {
    name: "Museumstraße",
    farbe: StreetColors.Rot,
    preis: 220,
    hypothek: 110,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 18,
    mieteGesamt: 36,
    miete1Haus: 90,
    miete2Haus: 250,
    miete3Haus: 700,
    miete4Haus: 875,
    mieteHotel: 1050,
    bauenKosten: 150,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
    takenBy: undefined,
  },
  {
    name: "Opernplatz",
    farbe: StreetColors.Rot,
    preis: 240,
    hypothek: 120,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 20,
    mieteGesamt: 40,
    miete1Haus: 100,
    miete2Haus: 300,
    miete3Haus: 750,
    miete4Haus: 1025,
    mieteHotel: 1100,
    bauenKosten: 150,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
    takenBy: undefined,
  },
  {
    name: "Lessingstraße",
    farbe: StreetColors.Gelb,
    preis: 260,
    hypothek: 130,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 22,
    mieteGesamt: 44,
    miete1Haus: 110,
    miete2Haus: 330,
    miete3Haus: 800,
    miete4Haus: 975,
    mieteHotel: 1150,
    bauenKosten: 150,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
    takenBy: undefined,
  },
  {
    name: "Schillerstraße",
    farbe: StreetColors.Gelb,
    preis: 260,
    hypothek: 130,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 22,
    mieteGesamt: 44,
    miete1Haus: 110,
    miete2Haus: 330,
    miete3Haus: 800,
    miete4Haus: 975,
    mieteHotel: 1150,
    bauenKosten: 150,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
    takenBy: undefined,
  },
  {
    name: "Goethestraße",
    farbe: StreetColors.Gelb,
    preis: 280,
    hypothek: 130,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 24,
    mieteGesamt: 48,
    miete1Haus: 120,
    miete2Haus: 360,
    miete3Haus: 850,
    miete4Haus: 1025,
    mieteHotel: 1200,
    bauenKosten: 150,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
    takenBy: undefined,
  },
  {
    name: "Rathausplatz",
    farbe: StreetColors.Grün,
    preis: 300,
    hypothek: 150,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 26,
    mieteGesamt: 52,
    miete1Haus: 130,
    miete2Haus: 390,
    miete3Haus: 900,
    miete4Haus: 1100,
    mieteHotel: 1275,
    bauenKosten: 200,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
    takenBy: undefined,
  },
  {
    name: "Hauptstraße",
    farbe: StreetColors.Grün,
    preis: 300,
    hypothek: 150,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 26,
    mieteGesamt: 52,
    miete1Haus: 130,
    miete2Haus: 390,
    miete3Haus: 900,
    miete4Haus: 1100,
    mieteHotel: 1275,
    bauenKosten: 200,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
    takenBy: undefined,
  },
  {
    name: "Bahnhofstraße",
    farbe: StreetColors.Grün,
    preis: 320,
    hypothek: 160,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 28,
    mieteGesamt: 56,
    miete1Haus: 150,
    miete2Haus: 450,
    miete3Haus: 1000,
    miete4Haus: 1200,
    mieteHotel: 1400,
    bauenKosten: 200,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
    takenBy: undefined,
  },
  {
    name: "Parkstraße",
    farbe: StreetColors.Blau,
    preis: 350,
    hypothek: 175,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 35,
    mieteGesamt: 70,
    miete1Haus: 175,
    miete2Haus: 500,
    miete3Haus: 1100,
    miete4Haus: 1300,
    mieteHotel: 1500,
    bauenKosten: 200,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
    takenBy: undefined,
  },
  {
    name: "Schlossallee",
    farbe: StreetColors.Blau,
    preis: 400,
    hypothek: 200,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 50,
    mieteGesamt: 100,
    miete1Haus: 200,
    miete2Haus: 600,
    miete3Haus: 1400,
    miete4Haus: 1700,
    mieteHotel: 2000,
    bauenKosten: 200,
    straße: true,
    bahnhof: false,
    sonderstraße: false,
    takenBy: undefined,
  },
  {
    name: "Südbahnhof",
    farbe: StreetColors.Schwarz,
    preis: 200,
    hypothek: 100,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 25,
    mieteGesamt: 0,
    miete1Haus: 25,
    miete2Haus: 50,
    miete3Haus: 100,
    miete4Haus: 200,
    mieteHotel: 0,
    bauenKosten: 0,
    straße: false,
    bahnhof: true,
    sonderstraße: false,
    takenBy: undefined,
  },
  {
    name: "Westbahnhof",
    farbe: StreetColors.Schwarz,
    preis: 200,
    hypothek: 100,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 25,
    mieteGesamt: 0,
    miete1Haus: 25,
    miete2Haus: 50,
    miete3Haus: 100,
    miete4Haus: 200,
    mieteHotel: 0,
    bauenKosten: 0,
    straße: false,
    bahnhof: true,
    sonderstraße: false,
    takenBy: undefined,
  },
  {
    name: "Nordbahnhof",
    farbe: StreetColors.Schwarz,
    preis: 200,
    hypothek: 100,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 25,
    mieteGesamt: 0,
    miete1Haus: 25,
    miete2Haus: 50,
    miete3Haus: 100,
    miete4Haus: 200,
    mieteHotel: 0,
    bauenKosten: 0,
    straße: false,
    bahnhof: true,
    sonderstraße: false,
    takenBy: undefined,
  },
  {
    name: "Hauptbahnhof",
    farbe: StreetColors.Schwarz,
    preis: 200,
    hypothek: 100,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 25,
    mieteGesamt: 0,
    miete1Haus: 25,
    miete2Haus: 50,
    miete3Haus: 100,
    miete4Haus: 200,
    mieteHotel: 0,
    bauenKosten: 0,
    straße: false,
    bahnhof: true,
    sonderstraße: false,
    takenBy: undefined,
  },
  {
    name: "Elektrizitätswerk",
    farbe: StreetColors.Weiß,
    preis: 150,
    hypothek: 75,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 0,
    mieteGesamt: 0,
    miete1Haus: 0,
    miete2Haus: 0,
    miete3Haus: 0,
    miete4Haus: 0,
    mieteHotel: 0,
    bauenKosten: 0,
    straße: false,
    bahnhof: false,
    sonderstraße: true,
    takenBy: undefined,
  },
  {
    name: "Wasserwerk",
    farbe: StreetColors.Weiß,
    preis: 150,
    hypothek: 75,
    hypothekisiert: false,
    anzahlHaus: 0,
    miete: 0,
    mieteGesamt: 0,
    miete1Haus: 0,
    miete2Haus: 0,
    miete3Haus: 0,
    miete4Haus: 0,
    mieteHotel: 0,
    bauenKosten: 0,
    straße: false,
    bahnhof: false,
    sonderstraße: true,
    takenBy: undefined,
  },
];
